Thursday, March 8, 2018 1:55:23 PM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FileBufferingReadStream'.
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.set_Position(Int64 value)
   at Web.Infrastructure.ExceptionHandling.ErrorFactory.captureBody(HttpContext context)
   at Web.Infrastructure.ExceptionHandling.ErrorFactory.GetError()
   at Web.Infrastructure.ExceptionHandling.CoreErrorLogger.Log(Exception ex)
**********************************************************
Thursday, March 8, 2018 1:55:24 PM
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'GUID', table 'Fernweh.dbo.Exceptions'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
ClientConnectionId:337161a2-7459-43db-ae1d-4480ef9fbf3a
Error Number:515,State:2,Class:16
**********************************************************
Thursday, March 8, 2018 1:55:24 PM
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'GUID', table 'Fernweh.dbo.Exceptions'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
ClientConnectionId:4c4f68ea-e747-4812-9880-dbd43eda207c
Error Number:515,State:2,Class:16
**********************************************************
Thursday, March 8, 2018 1:55:25 PM
System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
**********************************************************
Thursday, March 8, 2018 1:55:25 PM
System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
**********************************************************
Thursday, March 8, 2018 1:55:26 PM
System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
**********************************************************
Thursday, March 8, 2018 1:55:26 PM
System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
**********************************************************
Thursday, March 8, 2018 1:55:27 PM
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'GUID', table 'Fernweh.dbo.Exceptions'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
ClientConnectionId:337161a2-7459-43db-ae1d-4480ef9fbf3a
Error Number:515,State:2,Class:16
**********************************************************
Thursday, March 8, 2018 1:55:27 PM
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'GUID', table 'Fernweh.dbo.Exceptions'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
ClientConnectionId:337161a2-7459-43db-ae1d-4480ef9fbf3a
Error Number:515,State:2,Class:16
**********************************************************
Thursday, March 8, 2018 1:55:28 PM
System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
**********************************************************
Thursday, March 8, 2018 1:55:28 PM
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'GUID', table 'Fernweh.dbo.Exceptions'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
ClientConnectionId:337161a2-7459-43db-ae1d-4480ef9fbf3a
Error Number:515,State:2,Class:16
**********************************************************
Thursday, March 8, 2018 1:55:28 PM
System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
**********************************************************
Thursday, March 8, 2018 1:55:29 PM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FileBufferingReadStream'.
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.set_Position(Int64 value)
   at Web.Infrastructure.ExceptionHandling.ErrorFactory.captureBody(HttpContext context)
   at Web.Infrastructure.ExceptionHandling.ErrorFactory.GetError()
   at Web.Infrastructure.ExceptionHandling.CoreErrorLogger.Log(Exception ex)
**********************************************************
Thursday, March 8, 2018 1:55:29 PM
System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
**********************************************************
Thursday, March 8, 2018 1:55:29 PM
System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
**********************************************************
Thursday, March 8, 2018 1:55:29 PM
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FileBufferingReadStream'.
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.set_Position(Int64 value)
   at Web.Infrastructure.ExceptionHandling.ErrorFactory.captureBody(HttpContext context)
   at Web.Infrastructure.ExceptionHandling.ErrorFactory.GetError()
   at Web.Infrastructure.ExceptionHandling.CoreErrorLogger.Log(Exception ex)
**********************************************************
Thursday, March 8, 2018 1:55:29 PM
System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Core.Operations.Errors.ErrorAddCommand.<ProcessRequestAsync>d__2.MoveNext() in C:\dev\spa-starter-kit\src\Core\Operations\Errors\ErrorAddCommand.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Voodoo.Operations.Async.ExecutorAsync`2.<ExecuteAsync>d__3.MoveNext()
**********************************************************
